modelFlags = {
	["one_exhaust"] = "0x0",
	["double_exhaust"] = "0x2000",
}

vehicleHandlings = {
	[400] = { -- Porsche Cayenne Turbo
		["mass"] = 2000,
		["turnMass"] = 9900,
		["dragCoeff"] = 1.3,
		["centerOfMass"] = { 0.0, 0.1, -0.1 },
		["tractionMultiplier"] = 0.9,
		["tractionLoss"] = 0.9,
		["tractionBias"] = 0.49,
		["numberOfGears"] = 5,
		["maxVelocity"] = 165, -- 196km/h
		["engineAcceleration"] = 11,
		["engineInertia"] = 80,
		["driveType"] = "awd",
		["engineType"] = "petrol",
		["brakeDeceleration"] = 150,
		["brakeBias"] = 0.6,
		["steeringLock"] = 30,
		["suspensionFrontRearBias"] = 0.50,
		["suspensionLowerLimit"] = -0.11,
		["suspensionHighSpeedDamping"] = 0,
		["collisionDamageMultiplier"] = 0.6,

		["modelFlags"] = modelFlags["double_exhaust"],
	},
	[401] = { -- BMW M4
		["mass"] = 1400,
		["turnMass"] = 2200,
		["dragCoeff"] = 1.3,
		["centerOfMass"] = { 0.0, 0.1, -0.48 },
		["tractionMultiplier"] = 0.8,
		["tractionLoss"] = 0.9,
		["tractionBias"] = 0.49,
		["numberOfGears"] = 6,
		["maxVelocity"] = 223, -- 250km/h
		["engineAcceleration"] = 13,
		["engineInertia"] = 80,
		["driveType"] = "awd",
		["engineType"] = "petrol",
		["brakeDeceleration"] = 150,
		["brakeBias"] = 0.6,
		["steeringLock"] = 30,
		["suspensionFrontRearBias"] = 0.6,
		["suspensionLowerLimit"] = -0.005,
		["suspensionHighSpeedDamping"] = 0,
		["collisionDamageMultiplier"] = 0.6,

		["modelFlags"] = modelFlags["double_exhaust"],
	},
	[429] = { -- Banshee PP
		["mass"] = 1400,
		["turnMass"] = 2200,
		["dragCoeff"] = 1.3,
		["centerOfMass"] = { 0.0, 0.1, -0.25 },
		["tractionMultiplier"] = 1,
		["tractionLoss"] = 0.905,
		["tractionBias"] = 0.47,
		["numberOfGears"] = 5,
		["maxVelocity"] = 222, -- 350-tuningal 
		["engineAcceleration"] = 18,
		["engineInertia"] = 80,
		["driveType"] = "rwd",
		["engineType"] = "petrol",
		["brakeDeceleration"] = 150,
		["brakeBias"] = 0.6,
		["steeringLock"] = 30,
		["suspensionFrontRearBias"] = 0.47,
		["suspensionLowerLimit"] = -0.19,
		["suspensionHighSpeedDamping"] = 0,
		["collisionDamageMultiplier"] = 0.6,

		["modelFlags"] = modelFlags["double_exhaust"],
	},
	[514] = { -- 	Tanker
		["mass"] = 1400,
		["turnMass"] = 2200,
		["dragCoeff"] = 1.3,
		["centerOfMass"] = { 0.0, 0.1, -0.55 },
		["tractionMultiplier"] = 1,
		["tractionLoss"] = 1,
		["tractionBias"] = 0.35,
		["numberOfGears"] = 5,
		["maxVelocity"] = 120, -- 
		["engineAcceleration"] = 9,
		["engineInertia"] = 65,
		["driveType"] = "awd",
		["engineType"] = "petrol",
		["brakeDeceleration"] = 150,
		["brakeBias"] = 0.6,
		["steeringLock"] = 30,
		["suspensionFrontRearBias"] = 0.55,
		["suspensionLowerLimit"] = -0.18,
		["suspensionHighSpeedDamping"] = 0,
		["collisionDamageMultiplier"] = 0.6,

		["modelFlags"] = modelFlags["one_exhaust"],
	},
	[515] = { -- 	Volvo
		["maxVelocity"] = 120, -- 
		["engineAcceleration"] = 10,
		["engineInertia"] = 65,
		["tractionMultiplier"] = 0.75,
	},
	[403] = { -- 	Scania
		["mass"] = 1400,
		["turnMass"] = 2200,
		["dragCoeff"] = 1.3,
		["centerOfMass"] = { 0.0, 0.1, -0.55 },
		["tractionMultiplier"] = 1,
		["tractionLoss"] = 1,
		["tractionBias"] = 0.35,
		["numberOfGears"] = 5,
		["maxVelocity"] = 120, -- 
		["engineAcceleration"] = 11,
		["engineInertia"] = 65,
		["driveType"] = "awd",
		["engineType"] = "petrol",
		["brakeDeceleration"] = 150,
		["brakeBias"] = 0.6,
		["steeringLock"] = 30,
		["suspensionFrontRearBias"] = 0.55,
		["suspensionLowerLimit"] = -0.18,
		["suspensionHighSpeedDamping"] = 0,
		["collisionDamageMultiplier"] = 0.6,

		["modelFlags"] = modelFlags["one_exhaust"],
	},
}